### ISSUE TITLE
package 太大了，竟然有100M

### ISSUE THREAD

**Issue by zacksleo** [openUmbrella/react-native-root-tips#10]
http://registry.npm.taobao.org/react-native-root-tips/download/react-native-root-tips-1.0.0.tgz

package 太大了，导致无法安装

**Comment by zacksleo** [comment]
使用 .gitattribute 配置，然后忽略？ 试试这样可以么

**Comment by openUmbrella** [comment]
使用.npmignore来忽略example到npm上。




| |
openumbrella
邮箱：openumbrella@163.com
|

Signature is customized by Netease Mail Master

在2018年12月10日 16:38，zacks 写道：

使用 .gitattribute 配置，然后忽略？ 试试这样可以么
